name: Setup Apache Flex SDK
author: Josh Tynjala
description: Action to setup Apache Flex SDK

inputs:
  flex-version:
    description: "Version of the Apache Flex SDK (example: 4.16.1)"
    required: false

runs:
  using: "node16"
  main: "main.js"

branding:
  color: "blue"
  icon: "play"
