name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  # windows-adobe-air-version:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       with:
  #         flex-version: "4.16.1"
  #         air-version: "32.0"
  #         accept-air-license: true
  #     - name: Check executables
  #       run: |
  #         Get-Command mxmlc
  #         Get-Command compc
  #         Get-Command adt
  #         mxmlc -version
  #         compc -version
  #         adt -version

  # macos-adobe-air-version:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       with:
  #         flex-version: "4.16.1"
  #         air-version: "32.0"
  #         accept-air-license: true
  #     - name: Check executables
  #       run: |
  #         which mxmlc
  #         which compc
  #         which adt
  #         mxmlc -version
  #         compc -version
  #         adt -version

  # windows-harman-air-version:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       with:
  #         flex-version: "4.16.1"
  #         air-version: "50.0"
  #         accept-air-license: true
  #     - name: Check executables
  #       run: |
  #         Get-Command mxmlc
  #         Get-Command compc
  #         Get-Command adt
  #         mxmlc -version
  #         compc -version
  #         adt -version
  #         pwsh -Command {If (adt -license 2>&1 | Select-String -Quiet "DeveloperID="){Exit 1}Else{Exit 0}}

  macos-harman-air-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          flex-version: "4.16.1"
          air-version: "50.0"
          accept-air-license: true
      - name: Check executables
        run: |
          Get-Command mxmlc
          Get-Command compc
          Get-Command adt
          mxmlc -version
          compc -version
          adt -version
          adt -license 2>&1 | grep -q "No license file"
